# Generated by Django 5.2.16 on 2026-07-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('machine', models.CharField(max_length=100)),
                ('problems', models.TextField()),
                ('tools', models.TextField()),
                ('tools_total', models.DecimalField(decimal_places=0, max_digits=9)),
                ('cost', models.TextField()),
                ('cost_total', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
        ),
    ]
