# Generated by Django 6.0.7 on 2026-07-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_customer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'مشتری'},
        ),
        migrations.AddField(
            model_name='customer',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='جمع کل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cost',
            field=models.TextField(verbose_name='اجرت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cost_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='جمع هزینه اجرت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images/', verbose_name='عکس دستگاه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='machine',
            field=models.CharField(max_length=100, verbose_name='برند دستگاه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='problems',
            field=models.TextField(verbose_name='ایراد دستگاه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tools',
            field=models.TextField(verbose_name='هزینه قطعات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tools_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='جمع هزینه قطعات'),
        ),
    ]
