# Generated by Django 6.0.7 on 2026-07-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_customer_options_customer_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=9, verbose_name='جمع کل'),
            preserve_default=False,
        ),
    ]
