# Generated by Django 6.0.7 on 2026-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_customer_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='جمع کل'),
        ),
    ]
