# Generated by Django 6.0.7 on 2026-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='بدهی مشتری'),
        ),
    ]
