# Generated by Django 6.0.7 on 2026-07-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_customer_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='debt',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='بدهی مشتری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مشتری'),
        ),
    ]
