# Generated by Django 6.0.7 on 2026-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_customer_debt_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cost',
            field=models.TextField(blank=True, null=True, verbose_name='اجرت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tools',
            field=models.TextField(blank=True, null=True, verbose_name='هزینه قطعات'),
        ),
    ]
