# Generated by Django 6.0.7 on 2026-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_customer_cost_alter_customer_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.AddField(
            model_name='customer',
            name='partner_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='درصد همکار'),
        ),
    ]
