# Generated by Django 6.0.7 on 2026-07-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_customer_image_customer_partner_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='partner_fee',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='سهم همکار'),
        ),
    ]
